spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/caremyhome
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080